server:
  port: 8080
  servlet:
    application-display-name: conference-booking-service
    
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  sleuth:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connectionTimeout: 30000
      minimumIdle: 5
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: conferenceHikariCP
  h2: 
    console:
      enabled: true # Enabled for access h2 console for Dev
      path: /h2-console
  jpa:
    hibernate:
        ddl-auto: create
    database-platform:
        org.hibernate.dialect.H2Dialect
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org:
      springframework:
        web: INFO
        cloud:
          sleuth: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    
management:
  endpoints:
    web:
      base-path: /api/actuator
    exposure:
      include: "health" #configprops,logfile,metrics,loggers,caches,httptrace,prometheus
  tracing:
   sampling:
     probability: 1.0
   propagation:
     type: b3
     
app:
  maintenance-periods:
      - startTime: "09:00"
        endTime: "09:15"
      - startTime: "13:00"
        endTime: "13:15"
      - startTime: "17:00"
        endTime: "17:15"