INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY) VALUES (1,'Amaze',3);
INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY) VALUES (2,'Beauty',7);
INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY) VALUES (3,'Inspire',12);
INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY) VALUES (4,'Strive',20);