INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY,CREATION_DATE) VALUES (1,'Amaze',3,NOW());
INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY,CREATION_DATE) VALUES (2,'Beauty',7,NOW());
INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY,CREATION_DATE) VALUES (3,'Inspire',12,NOW());
INSERT INTO CONFERENCE_ROOM (CONFERENCE_ROOM_ID,NAME, MAX_CAPACITY,CREATION_DATE) VALUES (4,'Strive',20,NOW());